### ISSUE TITLE
MKS TS35 with Klipper

### ISSUE THREAD

**Issue by FabioMC** [makerbase-mks/Klipper-for-MKS-Boards#1]
Please, include MKS TS35 into LCD config.

**Comment by mks-viva** [comment]
Hi! Klipper currently does not support MKS TS3 screens, this may require modification of the source code.

**Comment by edouardkleinhans** [comment]
@mks-viva Maybe we can do a PR to klipper ?

**Comment by themacboy** [comment]
Any new about MKS TS25 support on klipper?

**Comment by akyrassan** [comment]
Hello,
would you be able to share the wiring diagram?
thanks in advance

**Comment by themacboy** [comment]
> > @mks-viva any new about MKS TS35 v2 support on klipper?
> > If yes I will rescue one to use there
> 
> You mean something like that?
> 
> Only figuring out how to calibrate the screen
> 
> ![TS35_photo_2021-09-28_21-14-46](https://user-images.githubusercontent.com/5961905/135367866-17bbcf1b-7d52-4416-8f76-aedb27c3df92.jpg)

Interesting ! Promising !

**Comment by willngton** [comment]
> Hello, would you be able to share the wiring diagram as well as the configuration file? thanks in advance

I have put together a draft on my finding and configuration, its fully operation including touch.

A friend create an easy on time scrip to install, considering you have already installed klipper, klipperscreen via:
https://github.com/th33xitus/kiauh



[MKS_TS35_PI_TELA_MKS.zip](https://github.com/makerbase-mks/Klipper-for-MKS-Boards/files/7584626/MKS_TS35_PI_TELA_MKS.zip)

[TS35_Rascunho_Klipper_RaspberryPI_ENv2.pdf](https://github.com/makerbase-mks/Klipper-for-MKS-Boards/files/7584627/TS35_Rascunho_Klipper_RaspberryPI_ENv2.pdf)

**Comment by willngton** [comment]
Video:

https://user-images.githubusercontent.com/5961905/142941528-6624a35b-c8c2-4f95-afc9-c99dc545c9e4.mp4

**Comment by willngton** [comment]
https://github.com/willngton/3DPrinterConfig/tree/main/mks_ts35

**Comment by akyrassan** [comment]
Thanks ,i will try it 👍

**Comment by mks-viva** [comment]
MKS Pi+MKS PI-TS35 and this way is the best.

**Comment by xojikia** [comment]
Hello, I did everything according to your instructions , The screen is working, it shows everything, but the touch screen is not working
MKS TS35

What is my problem?, can you help me?
Klipper / Mainsail
![MKS TS35](https://user-images.githubusercontent.com/105436263/201040817-aceafd2b-3e8b-4e5e-8f84-8ed6967afd05.jpg)

**Comment by willngton** [comment]
> https://github.com/willngton/3DPrinterConfig/tree/main/mks_ts35

Have you check the new version, https://github.com/fbeltrao-br/mksts35

A member of community put a better way of configure touch
