### ISSUE TITLE
Flashing Klipper firmware issue on Robin E3

### ISSUE THREAD

**Issue by omidta** [makerbase-mks/Klipper-for-MKS-Boards#10]
Please help.
I tried to flash my MKS Robin E3 by provided Robin_e3.bin but it sucked on 100%. I also made a new firmware by Klipper  based on the guide on generic-mks-robin-e3.cfg but no result. I disconnected my LCD but still the board didn't flashed

**Comment by willngton** [comment]
> Please help.
> I tried to flash my MKS Robin E3 by provided Robin_e3.bin but it sucked on 100%. I also made a new firmware by Klipper based on the guide on generic-mks-robin-e3.cfg but no result. I disconnected my LCD but still the board didn't flashed

Hi @omidta 

This is normal, you just need to make sure file Robin_e3.bin on the SD-card changed to Robin_e3.CUR, and Klipper will be on the board MCU, go ahead and config you favorite web interface (octoprint, fluidd or mainsail)

Kind regards.

**Comment by mks-viva** [comment]
1. You copy MKS Robin E3 path firmware bin file and update it
2. You need set you use the display screen
3. You need send 'firmware_restart' cammand

**Comment by omidta** [comment]
Thank you @willngton  you saved a lot of my time

**Comment by mks-viva** [comment]
So, I close this issues.
