### ISSUE TITLE
MKS Robin TFT35 v1.0 LCD support for klipper

### ISSUE THREAD

**Issue by mpalpha** [makerbase-mks/Klipper-for-MKS-Boards#12]
Maybe do something similar to BTT?
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1913

**Comment by jonathanrobichaud4** [comment]
I second this! I really want to use Klipper but it would be great to use the built in tft!

**Comment by mks-viva** [comment]
Like this: https://github.com/makerbase-mks/Klipper-for-MKS-Boards/issues/1

**Comment by mpalpha** [comment]
> Like this: #1

This is not the same screen. The MKS Robin TFT35 v1.0 is different than the MKS TS35 v2.0.

**Comment by ramaxa9** [comment]
any update? i have 2, dont know what i can do with them

**Comment by ABBAGABBA** [comment]
Hi everyone! Does anyone have any information about the possibility of implementing the MKS TFT35 connectivity?
