### ISSUE TITLE
Klipper on a MKS Robin Nano v2

### ISSUE THREAD

**Issue by themacboy** [makerbase-mks/Klipper-for-MKS-Boards#15]
Good morning,

in your screen shoot of the menuconfig you suggest to select:

Serial (on USART3 PB11/PB10)

Are you sure? I can't connect with this parameters.

**Comment by themacboy** [comment]
If I connect my TS35 screen I notice that the board is on "booting..."

Looks like the firmware is not working after the update. 

I have tryed with you precompiled bin and with my own compilation

**Comment by themacboy** [comment]
@mks-viva any idea about this issue?

**Comment by themacboy** [comment]
I answer my self.

Looking at klipper issues I have noticed that after make the firmware you must run the next script (to recode the output file):

./scripts/update_mks_robin.py ./out/klipper.bin ./out/Robin_nano35.bin

then you can flash the bin file and success with your configs.

 @mks-viva please add this in the readme file. Thx in advance !

**Comment by willngton** [comment]
> I answer my self.
> 
> Looking at klipper issues I have noticed that after make the firmware you must run the next script (to recode the output file):
> 
> ./scripts/update_mks_robin.py ./out/klipper.bin ./out/Robin_nano35.bin
> 
> then you can flash the bin file and success with your configs.
> 
> @mks-viva please add this in the readme file. Thx in advance !

If you have time, you can test TS35 connected to PI and use KlipperScreen
https://github.com/willngton/3DPrinterConfig/tree/main/mks_ts35

**Comment by mks-viva** [comment]
@themacboy If you use board exp1,exp2 for MKS TS35 when you use klipper, MKS TS35 cann't work, because the klipper firmware have not support it.

**Comment by themacboy** [comment]
> @themacboy If you use board exp1,exp2 for MKS TS35 when you use klipper, MKS TS35 cann't work, because the klipper firmware have not support it.
Thx, yes I know it.

The problem and solutionm was the one I have posted later.

bin file must be converted using the script:
./scripts/update_mks_robin.py ./out/klipper.bin ./out/Robin_nano35.bin

That was my real problem.

**Comment by themacboy** [comment]
> > I answer my self.
> > Looking at klipper issues I have noticed that after make the firmware you must run the next script (to recode the output file):
> > ./scripts/update_mks_robin.py ./out/klipper.bin ./out/Robin_nano35.bin
> > then you can flash the bin file and success with your configs.
> > @mks-viva please add this in the readme file. Thx in advance !
> 
> If you have time, you can test TS35 connected to PI and use KlipperScreen https://github.com/willngton/3DPrinterConfig/tree/main/mks_ts35

Yes, I read it two days ago. I wil give a try when possible ! Thx

**Comment by mks-viva** [comment]
MKS Pi + MKS PI-TS35 + your nano v2 and it's a good match. So, i will close it.
