### ISSUE TITLE
robin nano v1.2 not booting

### ISSUE THREAD

**Issue by Mudardepois** [makerbase-mks/Klipper-for-MKS-Boards#39]
When the TFT updating screen reaches 100%, it freezes. After a restart, the screen only displays "booting," and nothing else occurs.

**Comment by jpokorny12** [comment]
Hi, i have same problem. I use this setting for build firmware [https://stone-time.de/docs/allgemeine-anleitung-zum-erzeugen-einer-klipper-firmware/](url), but it didnt work. Now i try precompiled fw from this github, and it works ;)

**Comment by JasonChio365** [comment]
> When the TFT updating screen reaches 100%, it freezes. After a restart, the screen only displays "booting," and nothing else occurs.

Hello, I have also encountered the problem that the touch screen is frozen at 100%, do you have any solution?
![IMG20240120011402](https://github.com/makerbase-mks/Klipper-for-MKS-Boards/assets/157148316/45cfae16-844b-496b-a24c-5a83c53be5c1)

**Comment by ycq3** [comment]
1. 需要执行脚本转换固件`./scripts/update_mks_robin.py out/klipper.bin out/Robin_nano35.bin`
2. 需要配置`GPIO pins to set at micro-controllerstartup` 值为 `!PC6,!PD13`
我配置后成功启动，但是屏幕没有显示，我还在解决屏幕的显示问题。

**Comment by ColdBeer72** [comment]
> 1. Need to execute script to convert firmware`./scripts/update_mks_robin.py out/klipper.bin out/Robin_nano35.bin`
> 2. `GPIO pins to set at micro-controllerstartup`The value needs to be configured. `!PC6,!PD13`
>    After I configured it, it started successfully, but the screen did not display. I am still solving the screen display problem.

The screen will NEVER work. In the same way. There are some workarounds to make it work but not connected to three MKS Robin Nano board.
I don't know if you your point 2 is specific for a locked board, but it's definitely not necessary for a Klipper first install nor an update, on a working board..

**Comment by fred794** [comment]
Version: v0.12.0-166-g957475421
Would it be possible to compile in this version because it doesn't work for me?
