### ISSUE TITLE
MKS Lite 1.1 can't work

### ISSUE THREAD

**Issue by wudixiaobinbin** [makerbase-mks/Klipper-for-MKS-Boards#5]
Mother board is MKS Lite V1.1, step motor can't work, only shaking.

**Comment by mks-viva** [comment]
I test it ok: https://github.com/makerbase-mks/Klipper-for-MKS-Boards/tree/main/MKS%20Robin%20Lite%20V1.1
May be you need check your config or motor...

**Comment by wudixiaobinbin** [comment]
I test not ok. I can't find the python file, I want to make a bin file myself, may be the klipper version is different from us

**Comment by wudixiaobinbin** [comment]
motor is normaly worked with https://github.com/makerbase-mks/MKS-Robin/tree/master/MKS%20Robin%20Lite

**Comment by mks-viva** [comment]
So, you can use it. I will close this issues.

**Comment by wudixiaobinbin** [comment]
hey, my issue is klipper can't work on my MKS lite 1.1

**Comment by mks-viva** [comment]
![image](https://user-images.githubusercontent.com/16629551/128451459-bfbb122f-d783-4630-9cd9-979693bd2fb8.png)
?

**Comment by wudixiaobinbin** [comment]
you tell me to check my motor, I just tell you my motor is worked well, but can't work with klipper

**Comment by mks-viva** [comment]
You download my link firmware test?

**Comment by wudixiaobinbin** [comment]
Yes I used that firmware, And motor only shaking in place, can't move

**Comment by mks-viva** [comment]
Lite V1.1 uses pins to control the reference voltage, but I don’t see the Vref setting in the klipper firmware. You can remove the motor load and test it, if it is will move, so, maybe the current is too small.

**Comment by mks-viva** [comment]
https://github.com/makerbase-mks/Klipper-for-MKS-Boards/issues/4

**Comment by wudixiaobinbin** [comment]
Aha, Maybe that's the point, Z motor only can go down with heat bed

**Comment by mks-viva** [comment]
Yes, but I have not seen klipper's vref settings, so I suggest you not use klipper directly

**Comment by wudixiaobinbin** [comment]
Ok, thank you, maybe waiting for klipper update
