### ISSUE TITLE
MKS Nano V3 with BLTouch

### ISSUE THREAD

**Issue by FabioMC** [makerbase-mks/Klipper-for-MKS-Boards#7]
I am trying to setup BLTouch with Nano V3 on klipper but it is not clear for me which is the sensor pin and control pin. can someone clarify this point?

**Comment by mks-viva** [comment]
You can refer to : https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X/blob/main/hardware/MKS%20Robin%20Nano%20V3.0_004/MKS%20Robin%20Nano%20V3.0_004%20PIN.pdf
![image](https://user-images.githubusercontent.com/16629551/130306206-471b36a9-4ca9-4e0f-937d-20840c825cc1.png)
